### ISSUE TITLE
use new config option in Autotool

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/term-tasks#3]
These fields are new:
https://github.com/fmidue/term-tasks/blob/cdc1475491f9d1dfb7289659ec98aece16cc66a0/src/Records.hs#L34 https://github.com/fmidue/term-tasks/blob/cdc1475491f9d1dfb7289659ec98aece16cc66a0/src/Records.hs#L51 Not sure whether any work on the Autotool side is necessary to update the tasks, being able to use the new option.

**Comment by marcellussiegburg** [comment]
There is no amendment required
